/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _Migrations {
  name: string;
  timestamp: string;
}

export interface _MigrationsLock {
  id: string;
  is_locked: Generated<number>;
}

export interface DB {
  __migrations: _Migrations;
  __migrations_lock: _MigrationsLock;
}
