/**
 * Workflow Routes for Production
 *
 * HTTP endpoints for triggering and monitoring CF Workflows.
 * These routes are exposed in production (unlike actionRoutes which are dev-only).
 */

import { route } from "rwsdk/router";
import { env } from "cloudflare:workers";

// Import workflow bindings (generated at build time)
// This will be empty if no workflow actions exist
let workflowBindings: Record<string, { className: string; binding: string }> = {};

try {
  // Dynamic import to handle case where no workflows exist
  const workflows = await import("@hands/actions/workflows");
  workflowBindings = workflows.workflowBindings ?? {};
} catch {
  // No workflows generated - that's fine
}

/**
 * CF Workflow binding interface (minimal typing for runtime use)
 * The actual types are generated by wrangler and available at build time.
 */
interface WorkflowBinding {
  create(options?: { params?: unknown }): Promise<WorkflowInstanceHandle>;
  get(id: string): Promise<WorkflowInstanceHandle>;
}

interface WorkflowInstanceHandle {
  id: string;
  status(): Promise<{
    status: "queued" | "running" | "paused" | "complete" | "errored" | "terminated" | "unknown";
    output?: unknown;
    error?: { message: string };
  }>;
  sendEvent(event: { type: string; payload?: unknown }): Promise<void>;
  terminate(): Promise<void>;
}

/**
 * Get a workflow binding from env by action ID
 */
function getWorkflow(actionId: string): WorkflowBinding | null {
  const binding = workflowBindings[actionId];
  if (!binding) return null;

  const workflow = (env as unknown as Record<string, WorkflowBinding>)[binding.binding];
  return workflow ?? null;
}

/**
 * Workflow instance status response
 */
interface WorkflowStatus {
  id: string;
  status: "queued" | "running" | "paused" | "complete" | "errored" | "terminated" | "unknown";
  output?: unknown;
  error?: string;
}

async function getInstanceStatus(instance: WorkflowInstanceHandle): Promise<WorkflowStatus> {
  try {
    const status = await instance.status();
    return {
      id: instance.id,
      status: status.status,
      output: status.output,
      error: status.error?.message,
    };
  } catch (err) {
    return {
      id: instance.id,
      status: "unknown",
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export const workflowRoutes = [
  /**
   * List available workflows
   * GET /workflows
   */
  route("/workflows", {
    get: async () => {
      const workflows = Object.entries(workflowBindings).map(([id, { className }]) => ({
        id,
        className,
      }));

      return new Response(JSON.stringify(workflows), {
        headers: { "Content-Type": "application/json" },
      });
    },
  }),

  /**
   * Trigger a workflow
   * POST /workflows/:workflowId/run
   * Body: { input?: unknown }
   */
  route("/workflows/:workflowId/run", {
    post: async ({ request, params }) => {
      const workflowId = params.workflowId;
      const workflow = getWorkflow(workflowId);

      if (!workflow) {
        return new Response(
          JSON.stringify({ error: `Workflow not found: ${workflowId}` }),
          { status: 404, headers: { "Content-Type": "application/json" } }
        );
      }

      try {
        const body = (await request.json().catch(() => ({}))) as { input?: unknown };
        const instance = await workflow.create({ params: body.input });

        return new Response(
          JSON.stringify({
            instanceId: instance.id,
            workflowId,
            status: "started",
          }),
          { headers: { "Content-Type": "application/json" } }
        );
      } catch (err) {
        return new Response(
          JSON.stringify({
            error: `Failed to start workflow: ${err instanceof Error ? err.message : String(err)}`,
          }),
          { status: 500, headers: { "Content-Type": "application/json" } }
        );
      }
    },
  }),

  /**
   * Get workflow instance status
   * GET /workflows/:workflowId/instances/:instanceId
   */
  route("/workflows/:workflowId/instances/:instanceId", {
    get: async ({ params }) => {
      const { workflowId, instanceId } = params;
      const workflow = getWorkflow(workflowId);

      if (!workflow) {
        return new Response(
          JSON.stringify({ error: `Workflow not found: ${workflowId}` }),
          { status: 404, headers: { "Content-Type": "application/json" } }
        );
      }

      try {
        const instance = await workflow.get(instanceId);
        const status = await getInstanceStatus(instance);

        return new Response(JSON.stringify(status), {
          headers: { "Content-Type": "application/json" },
        });
      } catch (err) {
        return new Response(
          JSON.stringify({
            error: `Failed to get instance: ${err instanceof Error ? err.message : String(err)}`,
          }),
          { status: 500, headers: { "Content-Type": "application/json" } }
        );
      }
    },
  }),

  /**
   * Send event to a workflow instance (for waitForEvent)
   * POST /workflows/:workflowId/instances/:instanceId/event
   * Body: { type: string, payload: unknown }
   */
  route("/workflows/:workflowId/instances/:instanceId/event", {
    post: async ({ request, params }) => {
      const { workflowId, instanceId } = params;
      const workflow = getWorkflow(workflowId);

      if (!workflow) {
        return new Response(
          JSON.stringify({ error: `Workflow not found: ${workflowId}` }),
          { status: 404, headers: { "Content-Type": "application/json" } }
        );
      }

      try {
        const body = (await request.json()) as { type: string; payload?: unknown };
        const instance = await workflow.get(instanceId);

        // Send event to resume workflow
        await instance.sendEvent({ type: body.type, payload: body.payload });

        return new Response(
          JSON.stringify({ success: true, instanceId }),
          { headers: { "Content-Type": "application/json" } }
        );
      } catch (err) {
        return new Response(
          JSON.stringify({
            error: `Failed to send event: ${err instanceof Error ? err.message : String(err)}`,
          }),
          { status: 500, headers: { "Content-Type": "application/json" } }
        );
      }
    },
  }),

  /**
   * Terminate a workflow instance
   * DELETE /workflows/:workflowId/instances/:instanceId
   */
  route("/workflows/:workflowId/instances/:instanceId", {
    delete: async ({ params }) => {
      const { workflowId, instanceId } = params;
      const workflow = getWorkflow(workflowId);

      if (!workflow) {
        return new Response(
          JSON.stringify({ error: `Workflow not found: ${workflowId}` }),
          { status: 404, headers: { "Content-Type": "application/json" } }
        );
      }

      try {
        const instance = await workflow.get(instanceId);
        await instance.terminate();

        return new Response(
          JSON.stringify({ success: true, instanceId, status: "terminated" }),
          { headers: { "Content-Type": "application/json" } }
        );
      } catch (err) {
        return new Response(
          JSON.stringify({
            error: `Failed to terminate: ${err instanceof Error ? err.message : String(err)}`,
          }),
          { status: 500, headers: { "Content-Type": "application/json" } }
        );
      }
    },
  }),
];
