/**
 * hands build - Build workbook for production
 *
 * Spawns the runtime to perform the actual build.
 * This avoids the CLI needing to resolve workspace dependencies.
 */

import { spawn } from "bun"
import { existsSync } from "fs"
import { join, resolve } from "path"

interface BuildOptions {
  check?: boolean
  fix?: boolean
  json?: boolean
  strict?: boolean
  verbose?: boolean
}

export async function buildCommand(options: BuildOptions) {
  const workbookDir = process.cwd()

  // Verify this is a workbook directory
  const handsJsonPath = join(workbookDir, "hands.json")
  if (!existsSync(handsJsonPath)) {
    console.error("Error: hands.json not found")
    console.error("Run this command from a workbook directory")
    process.exit(1)
  }

  console.log("Building...")

  // Find the runtime build script
  const runtimeBuildPath = findRuntimeBuildPath()
  if (!runtimeBuildPath) {
    // Fallback: inline simple build
    await inlineBuild(workbookDir, options)
    return
  }

  // Spawn runtime build
  const proc = spawn({
    cmd: ["bun", runtimeBuildPath, workbookDir, options.verbose ? "--verbose" : ""],
    cwd: workbookDir,
    stdout: "inherit",
    stderr: "inherit",
  })

  const exitCode = await proc.exited
  if (exitCode !== 0) {
    process.exit(exitCode)
  }
}

/**
 * Find the runtime build script
 */
function findRuntimeBuildPath(): string | null {
  // Try workspace path (development)
  const devPath = resolve(import.meta.dir, "../../../runtime/src/build/cli.ts")
  if (existsSync(devPath)) {
    return devPath
  }

  // Try node_modules path (production)
  const nodeModulesPath = join(process.cwd(), "node_modules/@hands/runtime/src/build/cli.ts")
  if (existsSync(nodeModulesPath)) {
    return nodeModulesPath
  }

  return null
}

/**
 * Inline build for when runtime is not available
 * This is a minimal fallback that generates the basic structure
 */
async function inlineBuild(workbookDir: string, options: BuildOptions) {
  const { mkdir, writeFile } = await import("fs/promises")

  // Read hands.json
  const handsJsonPath = join(workbookDir, "hands.json")
  const config = JSON.parse(await Bun.file(handsJsonPath).text())

  const outputDir = join(workbookDir, config.build?.outDir || ".hands")

  // Create output directory
  await mkdir(outputDir, { recursive: true })

  // Generate wrangler.toml
  const wranglerContent = generateWranglerToml(config)
  await writeFile(join(outputDir, "wrangler.toml"), wranglerContent)

  // Generate worker.ts (minimal stub)
  const workerContent = generateWorkerStub(config)
  await writeFile(join(outputDir, "worker.ts"), workerContent)

  // Generate .gitignore
  await writeFile(join(outputDir, ".gitignore"), "# Auto-generated\n*\n")

  console.log(`Generated files in ${config.build?.outDir || ".hands"}/`)
}

function generateWranglerToml(config: any): string {
  const lines = [
    "# Generated by hands build",
    `name = "${config.name}"`,
    `main = "worker.ts"`,
    `compatibility_date = "2024-01-01"`,
  ]
  return lines.join("\n") + "\n"
}

function generateWorkerStub(config: any): string {
  return `// Generated by hands build
// Full build requires @hands/runtime

export default {
  async fetch(request: Request, env: any): Promise<Response> {
    return new Response("Workbook: ${config.name}");
  }
};
`
}
