/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env {
    DB: D1Database;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
