/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: fa8cd3c772b045fad29ad4e2bb233290)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
