/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: aedb82fe575dc1bf88e82d6ffcccd662)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
    durableNamespaces: "Database" | "SyncedStateServer";
  }
  interface Env {
    DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
    SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
