#!/usr/bin/env bun
/**
 * Bundle Tools Script
 *
 * Bundles each tool from tool/ into standalone files and generates
 * an embedded-tools.generated.ts that can be imported by index.ts.
 *
 * Run: bun run scripts/bundle-tools.ts
 * Output:
 *   - dist/tools/*.js (bundled tool files)
 *   - src/embedded-tools.generated.ts (tool content map)
 */

import { readdirSync, mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const AGENT_DIR = join(import.meta.dir, "..");
const TOOLS_DIR = join(AGENT_DIR, "tool");
const OUTPUT_DIR = join(AGENT_DIR, "dist", "tools");
const GENERATED_FILE = join(AGENT_DIR, "src", "embedded-tools.generated.ts");

// Get all tool files
// Skip: lint-block.ts (not a tool)
// Note: polars.ts is included but bundled with nodejs-polars as external (native addon)
const TOOL_FILES = readdirSync(TOOLS_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "lint-block.ts");

async function main() {
  console.log(`Bundling ${TOOL_FILES.length} tools...`);

  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Bundle each tool
  for (const file of TOOL_FILES) {
    const filepath = join(TOOLS_DIR, file);
    const outName = file.replace(".ts", ".js");

    // Native addons can't be bundled - must be external
    // nodejs-polars uses N-API bindings to Rust code
    const isPolars = file === "polars.ts";

    const result = await Bun.build({
      entrypoints: [filepath],
      outdir: OUTPUT_DIR,
      target: "bun",
      format: "esm",
      naming: outName,
      // Bundle all pure-JS dependencies directly into tools
      // Only native addons (nodejs-polars) must remain external
      external: isPolars ? ["nodejs-polars"] : [],
      minify: false,
    });

    if (!result.success) {
      console.error(`  ✗ ${file}`);
      for (const log of result.logs) {
        console.error(`    ${log}`);
      }
      process.exit(1);
    }

    console.log(`  ✓ ${file} → dist/tools/${outName}`);
  }

  console.log(`\nBundled ${TOOL_FILES.length} tools to dist/tools/`);

  // Generate embedded-tools.generated.ts
  console.log(`\nGenerating embedded-tools.generated.ts...`);

  const toolContents: Record<string, string> = {};
  for (const file of TOOL_FILES) {
    const jsFile = file.replace(".ts", ".js");
    const jsPath = join(OUTPUT_DIR, jsFile);
    toolContents[jsFile] = readFileSync(jsPath, "utf-8");
  }

  // Generate the TypeScript file
  const lines = [
    "/**",
    " * Auto-generated embedded tools",
    " * Generated by scripts/bundle-tools.ts",
    " * DO NOT EDIT MANUALLY",
    " */",
    "",
    "export const EMBEDDED_TOOLS: Record<string, string> = {",
  ];

  for (const [filename, content] of Object.entries(toolContents)) {
    // Escape backticks and ${} in the content
    const escaped = content
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$\{/g, "\\${");
    lines.push(`  "${filename}": \`${escaped}\`,`);
  }

  lines.push("};");
  lines.push("");

  writeFileSync(GENERATED_FILE, lines.join("\n"), "utf-8");
  console.log(`  ✓ Generated ${GENERATED_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
