/**
 * @hands/actions type declarations
 *
 * This is a virtual module generated by vite-plugin-workbook.
 * It contains all actions discovered from the workbook's actions/ directory.
 */

import type { ActionDefinition } from "../src/types/action";

/** Map of action ID to action definition */
export declare const actions: Record<string, ActionDefinition>;

/** Type of action IDs (union of all action keys) */
export type ActionId = keyof typeof actions;

/** Get an action by ID */
export declare function getAction(id: string): ActionDefinition | undefined;

/** List all actions with their IDs */
export declare function listActions(): Array<{ id: string; definition: ActionDefinition }>;
