/**
 * @hands/actions/workflows type declarations
 *
 * This is a virtual module generated by vite-plugin-workbook.
 * It contains CF WorkflowEntrypoint classes for workflow actions.
 *
 * If no workflow actions exist, this module exports empty bindings.
 */

/** Map of workflow ID to binding info */
export declare const workflowBindings: Record<string, { className: string; binding: string }>;

/** Type of workflow IDs (union of all workflow keys) */
export type WorkflowId = keyof typeof workflowBindings;

/** Get workflow binding info by ID */
export declare function getWorkflowBinding(
  id: string,
): { className: string; binding: string } | undefined;

// Workflow classes are dynamically generated based on actions
// They extend WorkflowEntrypoint<Env, unknown>
