"use client";

// Auto-generated by scripts/generate-registry.ts - DO NOT EDIT DIRECTLY
// Run: bun run generate

import * as React from "react";

import { HeatmapMap } from "./registry/components/maps/heatmap-map.js";
import { ScatterplotMap } from "./registry/components/maps/scatterplot-map.js";
import { HexagonMap } from "./registry/components/maps/hexagon-map.js";
import { GeoJsonMap } from "./registry/components/maps/geojson-map.js";
import { AspectRatio } from "./registry/components/ui/aspect-ratio.js";
import { AlertDialog, AlertDialogAction, AlertDialogContent, AlertDialogDescription, AlertDialogTitle, AlertDialogTrigger } from "./registry/components/ui/alert-dialog.js";
import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "./registry/components/ui/pagination.js";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./registry/components/ui/tabs.js";
import { ButtonGroup } from "./registry/components/ui/button-group.js";
import { Button } from "./registry/components/ui/button.js";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./registry/components/ui/card.js";
import { Slider } from "./registry/components/ui/slider.js";
import { InputGroup, InputGroupInput, InputGroupText } from "./registry/components/ui/input-group.js";
import { Popover, PopoverContent, PopoverTrigger } from "./registry/components/ui/popover.js";
import { Progress } from "./registry/components/ui/progress.js";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "./registry/components/ui/input-otp.js";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "./registry/components/ui/hover-card.js";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "./registry/components/ui/sheet.js";
import { Field, FieldDescription, FieldLabel } from "./registry/components/ui/field.js";
import { Input } from "./registry/components/ui/input.js";
import { ScrollArea } from "./registry/components/ui/scroll-area.js";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "./registry/components/ui/resizable.js";
import { Label } from "./registry/components/ui/label.js";
import { Toaster } from "./registry/components/ui/sonner.js";
import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuList, NavigationMenuTrigger } from "./registry/components/ui/navigation-menu.js";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./registry/components/ui/accordion.js";
import { Drawer, DrawerContent, DrawerDescription, DrawerTitle, DrawerTrigger } from "./registry/components/ui/drawer.js";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "./registry/components/ui/empty.js";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./registry/components/ui/tooltip.js";
import { Alert, AlertDescription, AlertTitle } from "./registry/components/ui/alert.js";
import { Switch } from "./registry/components/ui/switch.js";
import { Calendar } from "./registry/components/ui/calendar.js";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage } from "./registry/components/ui/breadcrumb.js";
import { RadioGroup, RadioGroupItem } from "./registry/components/ui/radio-group.js";
import { Command, CommandGroup, CommandInput, CommandItem, CommandList } from "./registry/components/ui/command.js";
import { Item, ItemContent, ItemDescription, ItemTitle } from "./registry/components/ui/item.js";
import { ToggleGroup, ToggleGroupItem } from "./registry/components/ui/toggle-group.js";
import { Avatar, AvatarFallback, AvatarImage } from "./registry/components/ui/avatar.js";
import { Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarTrigger } from "./registry/components/ui/menubar.js";
import { Kbd } from "./registry/components/ui/kbd.js";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "./registry/components/ui/dialog.js";
import { Badge } from "./registry/components/ui/badge.js";
import { Sidebar, SidebarContent, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider } from "./registry/components/ui/sidebar.js";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./registry/components/ui/table.js";
import { Separator } from "./registry/components/ui/separator.js";
import { Toggle } from "./registry/components/ui/toggle.js";
import { Checkbox } from "./registry/components/ui/checkbox.js";
import { Spinner } from "./registry/components/ui/spinner.js";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "./registry/components/ui/collapsible.js";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "./registry/components/ui/dropdown-menu.js";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./registry/components/ui/select.js";
import { Textarea } from "./registry/components/ui/textarea.js";
import { Skeleton } from "./registry/components/ui/skeleton.js";
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuTrigger } from "./registry/components/ui/context-menu.js";
import { FormControl, FormItem, FormLabel, FormMessage } from "./registry/components/ui/form.js";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "./registry/components/ui/carousel.js";
import { DataTable } from "./registry/components/data/data-table.js";
import { MetricCard } from "./registry/components/data/metric-card.js";

export const previews: Record<string, () => React.ReactNode> = {
  "heatmap-map": () => (
    <HeatmapMap
      data={[
        { lat: 37.7749, lng: -122.4194, weight: 10 },
        { lat: 37.7849, lng: -122.4094, weight: 20 },
      ]}
      latKey="lat"
      lngKey="lng"
      weightKey="weight"
      height={400}
    />
  ),
  "scatterplot-map": () => (
    <ScatterplotMap
      data={[
        { lat: 37.7749, lng: -122.4194, value: 100 },
        { lat: 34.0522, lng: -118.2437, value: 200 },
      ]}
      latKey="lat"
      lngKey="lng"
      radiusKey="value"
      height={400}
    />
  ),
  "hexagon-map": () => (
    <HexagonMap
      data={[
        { lat: 37.7749, lng: -122.4194 },
        { lat: 37.7849, lng: -122.4094 },
        { lat: 37.7649, lng: -122.4294 },
      ]}
      latKey="lat"
      lngKey="lng"
      height={400}
    />
  ),
  "geojson-map": () => (
    <GeoJsonMap
      data={{
        type: "FeatureCollection",
        features: [
          {
            type: "Feature",
            geometry: { type: "Point", coordinates: [-122.4194, 37.7749] },
            properties: { name: "San Francisco" }
          }
        ]
      }}
      height={400}
    />
  ),
  "aspect-ratio": () => (
    <AspectRatio ratio={16 / 9}>
      <img src="photo.jpg" alt="Photo" />
    </AspectRatio>
  ),
  "alert-dialog": () => (
    <AlertDialog>
      <AlertDialogTrigger>Delete</AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogTitle>Are you sure?</AlertDialogTitle>
        <AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
        <AlertDialogAction>Continue</AlertDialogAction>
      </AlertDialogContent>
    </AlertDialog>
  ),
  "pagination": () => (
    <Pagination>
      <PaginationContent>
        <PaginationItem><PaginationPrevious href="#" /></PaginationItem>
        <PaginationItem><PaginationLink href="#">1</PaginationLink></PaginationItem>
        <PaginationItem><PaginationNext href="#" /></PaginationItem>
      </PaginationContent>
    </Pagination>
  ),
  "tabs": () => (
    <Tabs defaultValue="account">
      <TabsList>
        <TabsTrigger value="account">Account</TabsTrigger>
        <TabsTrigger value="password">Password</TabsTrigger>
      </TabsList>
      <TabsContent value="account">
        Account settings here.
      </TabsContent>
      <TabsContent value="password">
        Password settings here.
      </TabsContent>
    </Tabs>
  ),
  "button-group": () => (
    <ButtonGroup>
      <Button>Left</Button>
      <Button>Center</Button>
      <Button>Right</Button>
    </ButtonGroup>
  ),
  "card": () => (
    <Card>
      <CardHeader>
        <CardTitle>Project Overview</CardTitle>
        <CardDescription>Summary of your current project status</CardDescription>
      </CardHeader>
      <CardContent>
        <p>Your project is on track with 85% completion.</p>
      </CardContent>
    </Card>
  ),
  "slider": () => (
    <Slider
      defaultValue={[50]}
      max={100}
      step={1}
    />
  ),
  "input-group": () => (
    <InputGroup>
      <InputGroupText>@</InputGroupText>
      <InputGroupInput placeholder="Username" />
    </InputGroup>
  ),
  "popover": () => (
    <Popover>
      <PopoverTrigger>Open</PopoverTrigger>
      <PopoverContent>
        Content goes here
      </PopoverContent>
    </Popover>
  ),
  "progress": () => (
    <Progress value={60} />
  ),
  "input-otp": () => (
    <InputOTP maxLength={6}>
      <InputOTPGroup>
        <InputOTPSlot index={0} />
        <InputOTPSlot index={1} />
        <InputOTPSlot index={2} />
      </InputOTPGroup>
    </InputOTP>
  ),
  "hover-card": () => (
    <HoverCard>
      <HoverCardTrigger>Hover me</HoverCardTrigger>
      <HoverCardContent>
        Additional information appears here
      </HoverCardContent>
    </HoverCard>
  ),
  "sheet": () => (
    <Sheet>
      <SheetTrigger asChild>
        <button>Open</button>
      </SheetTrigger>
      <SheetContent>
        <SheetHeader>
          <SheetTitle>Settings</SheetTitle>
          <SheetDescription>
            Make changes to your profile here.
          </SheetDescription>
        </SheetHeader>
      </SheetContent>
    </Sheet>
  ),
  "field": () => (
    <Field>
      <FieldLabel>Email</FieldLabel>
      <Input type="email" placeholder="Enter your email" />
      <FieldDescription>We'll never share your email.</FieldDescription>
    </Field>
  ),
  "scroll-area": () => (
    <ScrollArea className="h-72 w-48">
      <div>Long content that scrolls...</div>
    </ScrollArea>
  ),
  "resizable": () => (
    <ResizablePanelGroup direction="horizontal">
      <ResizablePanel defaultSize={50}>Panel 1</ResizablePanel>
      <ResizableHandle />
      <ResizablePanel defaultSize={50}>Panel 2</ResizablePanel>
    </ResizablePanelGroup>
  ),
  "label": () => (
    <Label htmlFor="email">Email Address</Label>
  ),
  "sonner": () => (
    <Toaster />
  ),
  "navigation-menu": () => (
    <NavigationMenu>
      <NavigationMenuList>
        <NavigationMenuItem>
          <NavigationMenuTrigger>Products</NavigationMenuTrigger>
          <NavigationMenuContent>Menu items here</NavigationMenuContent>
        </NavigationMenuItem>
      </NavigationMenuList>
    </NavigationMenu>
  ),
  "accordion": () => (
    <Accordion type="single" collapsible>
      <AccordionItem value="item-1">
        <AccordionTrigger>Question?</AccordionTrigger>
        <AccordionContent>Answer here.</AccordionContent>
      </AccordionItem>
    </Accordion>
  ),
  "drawer": () => (
    <Drawer>
      <DrawerTrigger>Open Drawer</DrawerTrigger>
      <DrawerContent>
        <DrawerTitle>Drawer Title</DrawerTitle>
        <DrawerDescription>Drawer content here.</DrawerDescription>
      </DrawerContent>
    </Drawer>
  ),
  "empty": () => (
    <Empty>
      <EmptyHeader>
        <EmptyTitle>No messages</EmptyTitle>
        <EmptyDescription>You don't have any messages yet.</EmptyDescription>
      </EmptyHeader>
    </Empty>
  ),
  "tooltip": () => (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger>Hover me</TooltipTrigger>
        <TooltipContent>
          <p>Helpful information</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  ),
  "alert": () => (
    <Alert>
      <AlertTitle>Heads up!</AlertTitle>
      <AlertDescription>You can use this to highlight important information.</AlertDescription>
    </Alert>
  ),
  "switch": () => (
    <div className="flex items-center space-x-2">
      <Switch id="airplane-mode" />
      <label htmlFor="airplane-mode">Airplane Mode</label>
    </div>
  ),
  "calendar": () => (
    <Calendar mode="single" />
  ),
  "breadcrumb": () => (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/">Home</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbPage>Current Page</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  ),
  "radio-group": () => (
    <RadioGroup defaultValue="option1">
      <div className="flex items-center space-x-2">
        <RadioGroupItem value="option1" id="option1" />
        <Label htmlFor="option1">Option 1</Label>
      </div>
    </RadioGroup>
  ),
  "command": () => (
    <Command>
      <CommandInput placeholder="Search..." />
      <CommandList>
        <CommandGroup heading="Actions">
          <CommandItem>New File</CommandItem>
          <CommandItem>Open</CommandItem>
        </CommandGroup>
      </CommandList>
    </Command>
  ),
  "item": () => (
    <Item>
      <ItemContent>
        <ItemTitle>User Name</ItemTitle>
        <ItemDescription>user@example.com</ItemDescription>
      </ItemContent>
    </Item>
  ),
  "toggle-group": () => (
    <ToggleGroup type="single">
      <ToggleGroupItem value="bold">Bold</ToggleGroupItem>
      <ToggleGroupItem value="italic">Italic</ToggleGroupItem>
      <ToggleGroupItem value="underline">Underline</ToggleGroupItem>
    </ToggleGroup>
  ),
  "avatar": () => (
    <Avatar>
      <AvatarImage src="profile.jpg" />
      <AvatarFallback>JD</AvatarFallback>
    </Avatar>
  ),
  "menubar": () => (
    <Menubar>
      <MenubarMenu>
        <MenubarTrigger>File</MenubarTrigger>
        <MenubarContent>
          <MenubarItem>New File</MenubarItem>
          <MenubarItem>Save</MenubarItem>
        </MenubarContent>
      </MenubarMenu>
    </Menubar>
  ),
  "kbd": () => (
    <Kbd>Ctrl+C</Kbd>
  ),
  "dialog": () => (
    <Dialog>
      <DialogTrigger>Open</DialogTrigger>
      <DialogContent>
        <DialogTitle>Dialog Title</DialogTitle>
        <DialogDescription>Dialog content goes here.</DialogDescription>
      </DialogContent>
    </Dialog>
  ),
  "badge": () => (
    <div className="flex gap-2">
      <Badge>New</Badge>
      <Badge variant="destructive">Error</Badge>
    </div>
  ),
  "sidebar": () => (
    <SidebarProvider>
      <Sidebar>
        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupLabel>Menu</SidebarGroupLabel>
            <SidebarGroupContent>
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton>Home</SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarGroupContent>
          </SidebarGroup>
        </SidebarContent>
      </Sidebar>
    </SidebarProvider>
  ),
  "ui-table": () => (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Name</TableHead>
          <TableHead>Email</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell>John Doe</TableCell>
          <TableCell>john@example.com</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  ),
  "separator": () => (
    <div>
      <div>Section 1</div>
      <Separator className="my-4" />
      <div>Section 2</div>
    </div>
  ),
  "button": () => (
    <div className="flex gap-2">
      <Button>Primary</Button>
      <Button variant="secondary">Secondary</Button>
      <Button variant="outline">Outline</Button>
    </div>
  ),
  "toggle-ui": () => (
    <Toggle aria-label="Toggle bold">B</Toggle>
  ),
  "checkbox": () => (
    <div className="flex items-center gap-2">
      <Checkbox id="terms" />
      <Label htmlFor="terms">Accept terms</Label>
    </div>
  ),
  "spinner": () => (
    <Spinner className="h-6 w-6" />
  ),
  "collapsible": () => (
    <Collapsible>
      <CollapsibleTrigger>Toggle</CollapsibleTrigger>
      <CollapsibleContent>Hidden content here.</CollapsibleContent>
    </Collapsible>
  ),
  "dropdown-menu": () => (
    <DropdownMenu>
      <DropdownMenuTrigger>Menu</DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuItem>Option 1</DropdownMenuItem>
        <DropdownMenuItem>Option 2</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  ),
  "select": () => (
    <Select>
      <SelectTrigger>
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent>
        <SelectItem value="apple">Apple</SelectItem>
        <SelectItem value="banana">Banana</SelectItem>
        <SelectItem value="orange">Orange</SelectItem>
      </SelectContent>
    </Select>
  ),
  "textarea": () => (
    <Textarea
      placeholder="Type your message here"
      rows={4}
    />
  ),
  "input": () => (
    <Input placeholder="Enter your email" type="email" />
  ),
  "skeleton": () => (
    <div className="flex items-center space-x-4">
      <Skeleton className="h-12 w-12 rounded-full" />
      <div className="space-y-2">
        <Skeleton className="h-4 w-[250px]" />
        <Skeleton className="h-4 w-[200px]" />
      </div>
    </div>
  ),
  "context-menu": () => (
    <ContextMenu>
      <ContextMenuTrigger>Right-click me</ContextMenuTrigger>
      <ContextMenuContent>
        <ContextMenuItem>Edit</ContextMenuItem>
        <ContextMenuItem>Delete</ContextMenuItem>
      </ContextMenuContent>
    </ContextMenu>
  ),
  "form": () => (
    <FormItem>
      <FormLabel>Email</FormLabel>
      <FormControl><Input placeholder="you@example.com" /></FormControl>
      <FormMessage />
    </FormItem>
  ),
  "carousel": () => (
    <Carousel>
      <CarouselContent>
        <CarouselItem>Slide 1</CarouselItem>
        <CarouselItem>Slide 2</CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  ),
  "data-table": () => (
    <DataTable
      data={[
        { name: "John", email: "john@example.com", role: "Admin" },
        { name: "Jane", email: "jane@example.com", role: "User" },
      ]}
      columns={[
        { key: "name", header: "Name" },
        { key: "email", header: "Email" },
        { key: "role", header: "Role" },
      ]}
    />
  ),
  "metric-card": () => (
    <MetricCard
      title="Total Revenue"
      value="$48,352"
      trend={{ value: 12.5, direction: "up" }}
      description="vs last month"
    />
  )
};
